apiVersion: v1
kind: Service
metadata:
  annotations:
    aistor.min.io/app: sts
  name: sts
  namespace: aistor
spec:
  ports:
  - name: https
    port: 4223
    targetPort: 4223
  selector:
    aistor.min.io/name: object-store-operator
  type: ClusterIP
