apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_keymanagers.aistor.min.io.yaml
- apps_v1_deployment_keymanager-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-keymanager-binding.yaml
- v1_serviceaccount_aistor-keymanager.yaml
