apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  #HELM+# annotations:
    #HELM+# {{- with $.Values.annotations }}
    #HELM+# {{- . | toYaml | nindent 4 }}
    #HELM+# {{- end }}
  labels:
    application-name: directpv.min.io
    application-type: CSIDriver
    directpv.min.io/created-by: kubectl-directpv
    directpv.min.io/version: v1beta1
    #HELM+# {{- with $.Values.labels }}
    #HELM+# {{- . | toYaml | nindent 4 }}
    #HELM+# {{- end }}
  name: directpv-min-io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
