apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_loadbalancers.aistor.min.io.yaml
- apps_v1_deployment_loadbalancer-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-loadbalancer-binding.yaml
- v1_serviceaccount_aistor-loadbalancer.yaml
