apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    aistor.min.io/name: aistor
  name: aistor
  namespace: aistor
spec:
  replicas: 1
  selector:
    matchLabels:
      aistor.min.io/name: aistor
  serviceName: aistor-hl
  template:
    metadata:
      labels:
        aistor.min.io/name: aistor
    spec:
      containers:
      - args:
        - server
        env:
        - name: AISTOR_CONFIG_DIR_PATH
          value: /data/config
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: quay.io/minio/aistor:RELEASE.2025-01-28T19-50-23Z
        imagePullPolicy: Always
        name: console
        ports:
        - containerPort: 8444
          name: http
        - containerPort: 7899
          name: control-plane
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /data
          name: console-data
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: aistor-sa
  volumeClaimTemplates:
  - metadata:
      name: console-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
