apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aistor

resources:
  - crds/aistor.min.io_serviceconfigurations.yaml
  - namespace.yaml
  - sa.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - statefulset.yaml
  - service.yaml
  - service-hl.yaml
  # also create the roles for AIStor operator
  - clusterrole_aistor-role.yaml
  - cluster-role-binding-install.yaml
