apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apps_v1_statefulset_aistor.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-role.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-sa-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-sa-binding-install.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-sa-binding.yaml
- v1_namespace_aistor.yaml
- v1_service_aistor-hl.yaml
- v1_service_aistor.yaml
- v1_serviceaccount_aistor-sa.yaml
