apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aistor-sa-binding-install
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aistor-role
subjects:
- kind: ServiceAccount
  name: aistor-sa
  namespace: aistor
