apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aistor
  namespace: aistor
  labels:
    aistor.min.io/name: aistor
spec:
  serviceName: aistor-hl
  selector:
    matchLabels:
      aistor.min.io/name: aistor
  replicas: 1
  template:
    metadata:
      labels:
        aistor.min.io/name: aistor
    spec:
      serviceAccountName: aistor-sa
      containers:
        - image: quay.io/minio/aistor:RELEASE.2025-01-28T19-50-23Z
          imagePullPolicy: IfNotPresent
          name: console
          env:
            - name: AISTOR_CONFIG_DIR_PATH
              value: /data/config
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http
              containerPort: 8444
            - name: control-plane
              containerPort: 7899
          args:
            - server
          volumeMounts:
            - mountPath: /data
              name: console-data
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
            allowPrivilegeEscalation: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: "OnRootMismatch"
  volumeClaimTemplates:
    - metadata:
        name: console-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
