apiVersion: v1
kind: Service
metadata:
  labels:
    aistor.min.io/name: aistor
  name: aistor-hl
  namespace: aistor
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8444
  - name: control-plane
    port: 7899
    protocol: TCP
  selector:
    aistor.min.io/name: aistor
