apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aistor
commonAnnotations:
  aistor.min.io/authors: MinIO, Inc.
  aistor.min.io/license: Enterprise
  aistor.min.io/support: https://subnet.min.io
  aistor.min.io/version: RELEASE.2024-04-12T17-44-35Z
resources:
  - base/namespace.yaml
  - base/service-account.yaml
  - base/cluster-role.yaml
  - base/cluster-role-binding.yaml
  - base/crds/
  - base/service.yaml
  - base/deployment-object-store.yaml
  - base/deployment-catalog.yaml
  - base/deployment-keymanager.yaml
  - base/deployment-loadbalancer.yaml
  - base/deployment-observe.yaml
  - base/deployment-warp.yaml
images:
  - name: quay.io/minio/aistor/operator
    newName: quay.io/minio/aistor/operator
    newTag: RELEASE.2024-09-23T16-32-06Z
