apiVersion: v1
kind: Service
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2024-10-24T06-18-32Z
  labels:
    aistor.min.io/name: object-store-operator
  name: object-store-operator
  namespace: aistor
spec:
  ports:
  - name: http
    port: 4221
  selector:
    aistor.min.io/name: object-store-operator
    operator: leader
  type: ClusterIP
