apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2024-11-13T09-02-52Z
  name: aistor-inference
  namespace: aistor
