apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_adminjobs.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_aihubs.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_catalogs.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_inferences.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_keymanagers.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_loadbalancers.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_objectstores.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_observes.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_policybindings.sts.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_prompts.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_serviceconfigurations.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_serviceregistries.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_warps.aistor.min.io.yaml
- apps_v1_deployment_aihub-operator.yaml
- apps_v1_deployment_catalog-operator.yaml
- apps_v1_deployment_inference-operator.yaml
- apps_v1_deployment_keymanager-operator.yaml
- apps_v1_deployment_loadbalancer-operator.yaml
- apps_v1_deployment_object-store-operator.yaml
- apps_v1_deployment_observe-operator.yaml
- apps_v1_deployment_prompt-operator.yaml
- apps_v1_deployment_warp-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-role.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-tokenreview-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-binding.yaml
- v1_namespace_aistor.yaml
- v1_service_object-store-operator.yaml
- v1_service_sts.yaml
- v1_serviceaccount_aistor-adminjob.yaml
- v1_serviceaccount_aistor-aihub.yaml
- v1_serviceaccount_aistor-catalog.yaml
- v1_serviceaccount_aistor-inference.yaml
- v1_serviceaccount_aistor-keymanager.yaml
- v1_serviceaccount_aistor-loadbalancer.yaml
- v1_serviceaccount_aistor-object-store.yaml
- v1_serviceaccount_aistor-observe.yaml
- v1_serviceaccount_aistor-prompt.yaml
- v1_serviceaccount_aistor-warp.yaml
