apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
  name: aistor-warp
  namespace: aistor
