apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aistor
  namespace: aistor
spec:
  selector:
    matchLabels:
      aistor.min.io/name: aistor
  serviceName: aistor-hl
  template:
    spec:
      containers:
        - name: console
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: console-data
      spec:
        storageClassName: gp2
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
