apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minio-operator-delete-ns-role
  namespace: aistor
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - delete
