apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_adminjobs.aistor.min.io.yaml
- apps_v1_deployment_adminjob-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-adminjob-binding.yaml
- v1_serviceaccount_aistor-adminjob.yaml
