apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_prompts.aistor.min.io.yaml
- apps_v1_deployment_prompt-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-prompt-binding.yaml
- v1_serviceaccount_aistor-prompt.yaml
