apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ClusterRoleBinding.yaml
  - ClusterRole.yaml
  - directpvdrives.directpv.min.io.yaml
  - Namespace.yaml
  - ServiceAccount.yaml
