apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- apiextensions.k8s.io_v1_customresourcedefinition_objectstores.aistor.min.io.yaml
- apiextensions.k8s.io_v1_customresourcedefinition_policybindings.sts.min.io.yaml
- apps_v1_deployment_object-store-operator.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-role.yaml
- rbac.authorization.k8s.io_v1_clusterrole_aistor-tokenreview-role.yaml
- rbac.authorization.k8s.io_v1_clusterrolebinding_aistor-object-store-binding.yaml
- v1_service_object-store-operator.yaml
- v1_service_sts.yaml
- v1_serviceaccount_aistor-object-store.yaml
